// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		BackToTop: typeof import('./src/components/BackToTop.vue')['default'];
		ClassEvent: typeof import('./src/components/ClassEvent.vue')['default'];
		ClassMethod: typeof import('./src/components/ClassMethod.vue')['default'];
		ClassOverview: typeof import('./src/components/ClassOverview.vue')['default'];
		ClassProperty: typeof import('./src/components/ClassProperty.vue')['default'];
		Codeblock: typeof import('./src/components/Codeblock.vue')['default'];
		ExpandableTypes: typeof import('./src/components/ExpandableTypes.vue')['default'];
		Footer: typeof import('./src/components/Footer.vue')['default'];
		HeroiconsOutlineArrowNarrowUp: typeof import('~icons/heroicons-outline/arrow-narrow-up')['default'];
		HeroiconsOutlineArrowRight: typeof import('~icons/heroicons-outline/arrow-right')['default'];
		HeroiconsOutlineCheck: typeof import('~icons/heroicons-outline/check')['default'];
		HeroiconsOutlineChevronDown: typeof import('~icons/heroicons-outline/chevron-down')['default'];
		HeroiconsOutlineChevronRight: typeof import('~icons/heroicons-outline/chevron-right')['default'];
		HeroiconsOutlineChevronUp: typeof import('~icons/heroicons-outline/chevron-up')['default'];
		HeroiconsOutlineClipboardCheck: typeof import('~icons/heroicons-outline/clipboard-check')['default'];
		HeroiconsOutlineClipboardCopy: typeof import('~icons/heroicons-outline/clipboard-copy')['default'];
		HeroiconsOutlineCode: typeof import('~icons/heroicons-outline/code')['default'];
		HeroiconsOutlineDownload: typeof import('~icons/heroicons-outline/download')['default'];
		HeroiconsOutlineExternalLink: typeof import('~icons/heroicons-outline/external-link')['default'];
		HeroiconsOutlineMenu: typeof import('~icons/heroicons-outline/menu')['default'];
		HeroiconsOutlineMinus: typeof import('~icons/heroicons-outline/minus')['default'];
		HeroiconsOutlineMoon: typeof import('~icons/heroicons-outline/moon')['default'];
		HeroiconsOutlinePlus: typeof import('~icons/heroicons-outline/plus')['default'];
		HeroiconsOutlineSearch: typeof import('~icons/heroicons-outline/search')['default'];
		HeroiconsOutlineSun: typeof import('~icons/heroicons-outline/sun')['default'];
		HeroiconsOutlineX: typeof import('~icons/heroicons-outline/x')['default'];
		InstallButton: typeof import('./src/components/InstallButton.vue')['default'];
		Logo: typeof import('./src/components/Logo.vue')['default'];
		Navbar: typeof import('./src/components/Navbar.vue')['default'];
		ParameterTable: typeof import('./src/components/ParameterTable.vue')['default'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
		See: typeof import('./src/components/See.vue')['default'];
		Sidebar: typeof import('./src/components/Sidebar.vue')['default'];
		SourceButton: typeof import('./src/components/SourceButton.vue')['default'];
		Spinner: typeof import('./src/components/Spinner.vue')['default'];
		Stats: typeof import('./src/components/Stats.vue')['default'];
		SWBanner: typeof import('./src/components/SWBanner.vue')['default'];
		TypeLink: typeof import('./src/components/TypeLink.vue')['default'];
		Types: typeof import('./src/components/Types.vue')['default'];
	}
}

export {};
